# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build project

on:
  push:
    branches:
      - master
      - develop
      - testing
  pull_request:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11.0.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      REPO_GITHUB: docker.pkg.github.com/alamer/spring-gradle-github-actions/spring-gradle-github-actions
    steps:
      - uses: actions/checkout@v1
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
      - name: login to Github Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker for github image
        run: docker build -t $REPO_GITHUB:latest -t $REPO_GITHUB:${GITHUB_SHA::8} .
      - name: Publish Docker image in github
        run: docker push $REPO_GITHUB